on: push
name: CI/CD
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - run: npm i

      - run: npm run lint

  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat.nvmrc)
        id: nvm

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - run: npm install

      - run: node scripts/build

      - uses: actions/upload-artifact@v1
        with:
          name: website
          path: dist

  deploy:
    name: Deploy Website
    if: github.ref == 'refs/heads/master'
    needs: [build, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: website
          path: dist

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USER }}
          PORT: ${{ secrets.SSH_PORT }}
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: "dist/*"
          strip_components: 1
          rm: true
          target: "/www/tampermonkey"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: for x in `cd /www/tampermonkey/ && find -type f -not -name ".*" | sed 's?^./?https://tampermonkey.g5.dk/?'` ; do cache-purge $x ; done
